# .streamlit/secrets.toml

API_KEY = "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"

sql_user = "root"
sql_password = "cyccu4-Pofzoh-wywvuw"
sql_host = "34.130.202.122"
sql_database = "chatrecords"

